# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-build-check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-check-on-ubuntu:
    name: build-check on ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.1.3', '4.2.1']
        os: [ubuntu-latest]

    steps:
      - name: install dependency
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
      
      - uses: actions/checkout@v3
      
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "knitr","doParallel", "foreach", "ggplot2", "ggrepel", "pheatmap", "progress", "RColorBrewer", "reshape2", "rmarkdown", "prettydoc", "correlation"))
        shell: Rscript {0}
        
      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
        
  build-check-on-windows:
    name: build-check on windows
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.1.3', '4.2.1']
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "knitr","doParallel", "foreach", "ggplot2", "ggrepel", "pheatmap", "progress", "RColorBrewer", "reshape2", "rmarkdown", "prettydoc", "correlation"))
        shell: Rscript {0}
        
      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
  
  build-check-on-macos:
    name: build-check on macos
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.3', '4.2.1']
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "knitr","doParallel", "foreach", "ggplot2", "ggrepel", "pheatmap", "progress", "RColorBrewer", "reshape2", "rmarkdown", "prettydoc", "correlation"))
        shell: Rscript {0}
        
      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
